AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'bin/pg_export'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 200

Style/ParallelAssignment:
  Enabled: false

Documentation:
  Enabled: false
