AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockLength:
  Exclude:
    - 'bin/pg_export'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 200

Lint/AmbiguousOperator:
  Exclude:
    - 'lib/pg_export/configuration.rb'

Style/AlignArray:
  Exclude:
    - 'spec/configuration_spec.rb'

Style/ParallelAssignment:
  Enabled: false

Documentation:
  Enabled: false
