AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'bin/pg_export'
  ExcludedMethods: ['describe', 'context']

Metrics/LineLength:
  Max: 200

Style/ParallelAssignment:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Documentation:
  Enabled: false
